[package]
name = "qvfs"
version = "2.1.0"
edition = "2021"
authors = ["Strale <strahinjastojanovic826@gmail.com>"]
description = "A quaternary virtual file system (QVFS) simulator based on 4-state logic."
license = "AGPL-3.0-or-later" 
repository = "https://github.com/strahinjastojanovic826-code/qvfs"
readme = "README.md"
keywords = ["vfs", "quaternary", "filesystem", "simulation"]
categories = ["filesystem", "emulators"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
